### ISSUE TITLE
Why does .set_timeout do nothing?

### ISSUE THREAD

**Issue by mkpankov** [berkowski/tokio-serial#14]
https://docs.rs/tokio-serial/0.8.0/src/tokio_serial/lib.rs.html#189

```rust
    fn set_timeout(&mut self, _: Duration) -> ::Result<()> {
        Ok(())
    }
```

**Comment by ndusart** [comment]
Because we need it for implementing `SerialPort` trait.

See comment in #15

**Comment by mkpankov** [comment]
Thanks

**Comment by rise0chen** [comment]
Maybe, we should return `Err` if we not support it
