### ISSUE TITLE
No AsyncRead for Serial

### ISSUE THREAD

**Issue by mkpankov** [berkowski/tokio-serial#2]
Old [`Io`](https://docs.rs/tokio-core/0.1/tokio_core/io/trait.Io.html) has been moved to separate crate - [tokio-io](https://docs.rs/tokio-io/0.1.1/tokio_io/).

It has `AsyncRead` trait that's useful for many things, for example reading serial port line by line using [`Lines`](https://docs.rs/tokio-io/0.1.1/tokio_io/io/fn.lines.html).

It would be good to move to new tokio-io and provide new traits.

**Comment by berkowski** [comment]
lexxvir submitted #1 and should have addressed the tokio-io migration.  I haven't gotten around to doing any testing of it and so haven't made a new release.  If you've got something depending on those traits then please use the current head on master and let me know of any issues.

**Comment by berkowski** [comment]
Included #1 w/ release v0.5.0  Marking this closed for now.
