### ISSUE TITLE
tokio 1.0

### ISSUE THREAD

**Issue by anton-dutov** [berkowski/tokio-serial#32]
tokio 1.0 released, now it's stable

**Comment by berkowski** [comment]
I'll finally have time to work on this, but first up is getting berkowski/mio-serial#23 resolved.

**Comment by georgmu** [comment]
I was testing the v4.4.0 branch on linux and my read fails. I have a write request/read response setup with a USB PIO adapter to poll the state of connected pins.
The `AsyncRead` impl in src/unix.rs takes the OK path (`_result` is `Ok(6)`), but the 6 bytes do not end in the buffer.

The setup is similar to the `serial_println.rs` example.

Is there any further info or help I could provide?

**Comment by georgmu** [comment]
I investigated the issue and created pull #35 to fix it.

**Comment by ColinFinck** [comment]
I've implemented the missing Windows part for tokio 1.x support in https://github.com/enlyze/tokio-serial/tree/v4.4.0_serialstream_multiplatform
See also #39

This works well for me under Windows and Linux.
Requires pinning branches/revisions in Cargo.toml as long as they are not merged to master and released on crates.io. But other than that, I'm finally able to use serial ports with mio 0.7.x and tokio 1.x :)

**Comment by berkowski** [comment]
closing now that 5.4.0-beta1 is on crates.io.
