### ISSUE TITLE
please upgrade tokio to latest version

### ISSUE THREAD

**Issue by timchenxiaoyu** [berkowski/tokio-serial#38]
current tokio version : 1.6.0

**Comment by ColinFinck** [comment]
I've implemented the missing Windows part for tokio 1.x support in https://github.com/enlyze/tokio-serial/tree/v4.4.0_serialstream_multiplatform
See also #39

This works well for me under Windows and Linux.
Requires pinning branches/revisions in Cargo.toml as long as they are not merged to master and released on crates.io. But other than that, I'm finally able to use serial ports with mio 0.7.x and tokio 1.x :)

**Comment by berkowski** [comment]
closing now that 5.4.0-beta1 is on crates.io
