### ISSUE TITLE
Simultaneous read and write

### ISSUE THREAD

**Issue by katyo** [berkowski/tokio-serial#47]
Usually serial ports is duplex so it might allow the simultaneous reading and writing operations.
Is there any way to decompose port to source and sink to use both independently for receiving and sending data?

**Comment by berkowski** [comment]
Should be possible but I don't think it's a async-specific capability.  I'd think the proper way to do it would be to split the serial port into Tx and Rx halves in [serialport-rs](https://gitlab.com/susurrus/serialport-rs) and then mirror the features up the chain through `mio-serial` and `tokio-serial`

**Comment by katyo** [comment]
As temporary workaround I open port twice. First instance I use only for receiving the second for sending.

**Comment by berkowski** [comment]
neat.

Be aware that opening the same port twice might not work forever: https://gitlab.com/susurrus/serialport-rs/-/issues/109

**Comment by ndusart** [comment]
@katyo I'm using `tokio::io::split` without any issue for reading/writing concurrently.

**Comment by Ladvien** [comment]
Hey @ndusart and all, I appreciate the mentioned of `tokio::io::split` as I was confused on how to get a single stream to send and receive.  I've created an example on issue #20 demonstrating its usage.

https://github.com/berkowski/tokio-serial/issues/20#issuecomment-1114301487
