### ISSUE TITLE
List library on Tokio Third party page?

### ISSUE THREAD

**Issue by RadicalZephyr** [berkowski/tokio-serial#5]
Hi there! First off, thanks for making this library! I've just started using it but it saved me a ton of time.

I thought it might be useful for others to list this lib on the [Tokio Third Party](https://tokio.rs/docs/going-deeper-tokio/third-party/) page.  I can submit the PR, I just didn't want to do it without letting you know.

Cheers!

**Comment by berkowski** [comment]
If you're finding it useful, sure!  Feel free to submit the PR (and thanks!).
