### ISSUE TITLE
Write blocks for some seconds

### ISSUE THREAD

**Issue by gabrik** [berkowski/tokio-serial#52]
First, thank you for this very useful crate.

I encountered an issue, I'm currently implementing a Serial kind of transport for [Eclipse Zenoh](https://github.com/eclipse-zenoh/) and I faced a very strange issue, after some message exchange the `write(buf).await` seems to block and it does not actually send the data to the other side. 

I added some logs to check ( if you are interested you can look at them [here](https://github.com/gabrik/zenoh/blob/feat/serial-transport/io/zenoh-links/zenoh-link-serial/src/unicast.rs#L79))

and from the log, I can see that the `ACTUALLY WRITTEN` is never printed.

```
[2022-04-28T13:02:27Z ERROR zenoh_link_serial::unicast] TO SERIAL 41 : [27, 00, 44, 0A, F8, FB, C0, 42, 20, 8A, AA, 39, 4E, 11, 1D, 52, B4, BF, 45, 38, 5B, 87, 6A, 13, 24, 62, 87, 72, 66, 43, E9, 0A, 2B, 7E, C5, B2, 15, 7A, 8E, 79, B7]
[2022-04-28T13:02:27Z ERROR zenoh_link_serial::unicast] ACTUALLY WRITTEN 41 bytes
[2022-04-28T13:02:27Z ERROR zenoh_link_serial::unicast] FROM SERIAL: [06, 00]
[2022-04-28T13:02:27Z ERROR zenoh_link_serial::unicast] FROM SERIAL: [64, 0A, 81, F8, B7, 71]
[2022-04-28T13:02:29Z ERROR zenoh_link_serial::unicast] TO SERIAL 3 : [01, 00, 08]
....
```

Any idea? I understand that the serial is "slow" but being stuck forever is quite strange.

This is the configuration used when opening the serial
```
let port = tokio_serial::new(&path, 9_600)
            .data_bits(DataBits::Eight)
            .flow_control(FlowControl::None)
            .parity(Parity::Odd)
            .stop_bits(StopBits::Two)
            .open_native_async()
``` 

Already tried different baud rates and flow control strategies.

**Comment by estokes** [comment]
What is on the other side? Did you try to cut it down to a minimal example? 

One possible explanation is that you have an async task that does something blocking, and that is sharing a hardware thread with the task talking to the serial port. This is one reason why a minimal example is important.

**Comment by gabrik** [comment]
On the other side, there is a reading task that 
Anyway I'll try to have a minimal reproducible example and come back to this issue

**Comment by gabrik** [comment]
Hi I managed to reproduce it with this snippet of code:

```rust
use clap::Parser;
use tokio_serial::SerialPortBuilderExt;
use tokio::io::AsyncReadExt;
use tokio::io::AsyncWriteExt;
use tokio_serial::StopBits;
use std::time::Duration;
// use tokio_serial::SerialPort;
use tokio_serial::{DataBits, Parity, FlowControl};
use rand::Rng;


static DEFAULT_INTERVAL: &str = "1.0";

#[derive(Parser, Debug)]
struct Args {
    port: String,
    #[clap(short, long)]
    server: bool,
    #[clap(short, long, default_value = DEFAULT_INTERVAL)]
    interval: f64,
}


#[tokio::main]
async fn main() -> tokio_serial::Result<()> {

    let args = Args::parse();
    let mut buff = [0u8;65535];

    println!("Arguments: {:?}", args);

    let mut port = tokio_serial::new(args.port, 9600)
        .data_bits(DataBits::Eight)
        .flow_control(FlowControl::None)
        .parity(Parity::Odd)
        .stop_bits(StopBits::Two)
        .open_native_async()?;

    #[cfg(unix)]
    port.set_exclusive(false)
        .expect("Unable to set serial port exclusive to false");
    if args.server {



        loop {

            // println!(">> Bytes to write {}", port.bytes_to_write()?);
            // println!(">> Bytes to read {}", port.bytes_to_read()?);

            tokio::time::sleep(Duration::from_millis(100)).await;
            let read = port.read(&mut buff).await?;
            if read > 0 {
                println!(">> Read {read} bytes: {:02X?}", &buff[0..read]);
            }

            let mut written = 0;
            while written < read {
                written += port.write(&buff).await?;
            }

            println!("<< Wrote {written} bytes: {:02X?}", &buff[0..written]);


        }
    } else {

        let mut rng = rand::thread_rng();



        loop {
            tokio::time::sleep(Duration::from_secs_f64(args.interval)).await;

            let total = rng.gen_range(1..32);

            let data: Vec<u8> = (0..total).map(|_| rng.gen_range(1..255) ).collect();

            let mut written = 0;
            while written < data.len() {
                written += port.write(&data).await?;
            }
            port.flush().await?;

            println!("<< Wrote {} bytes", written);


            let read = port.read(&mut buff).await?;
            if read > 0 {
                // println!(">> Read {read} bytes: {:02X?}", &buff[0..read]);
                println!(">> Read {read} bytes");
            }
        }
    }
}

```

It is like an "echo server" so the client writes something to the server that replies back.
After some exchange, the server stops sending messages, the server is stuck in `port.write(&buff).await`

Can it be that some buffers are full and therefore the writer is stuck?

**Comment by gabrik** [comment]
I guess it is a buffer issue and a lack of synchronization issue, so I'm defining a frame format to send the data over the serial that will include some synchronization, that should solve this issue.

**Comment by gabrik** [comment]
As expected solved it using some framing, for the interested ones: https://github.com/gabrik/rust-serial-tests/blob/master/src/zserial.rs
