### ISSUE TITLE
Issue with `available_ports` returning directories for the port names on linux

### ISSUE THREAD

**Issue by archfz** [berkowski/tokio-serial#57]
```rust
let ports = tokio_serial::available_ports().unwrap();
println!("Found ports: {:?}", ports);
```

The above code will print out: 
```
Found ports: [SerialPortInfo { port_name: "/sys/class/tty/ttyACM0", port_type: Unknown }, SerialPortInfo { port_name: "/sys/class/tty/ttyACM1", port_type: Unknown }]
```

When using a port name like this I will get the following error when trying to open the port: ` /sys/class/tty/ttyACM0 port: Is a directory`
Checking with `[[ -L "/sys/class/tty/ttyACM1" && -f "/sys/class/tty/ttyACM1" ]] || echo "Not a file"` I indeed get that it's a directory symlink.

Interestingly when I explicitly install `serialport = "4.2.0"` it fixes the issue, and the port names become like `/dev/ttyACM1`.

## Versions

Ubuntu 22.04 LTS

cargo 1.61.0 (a028ae4 2022-04-29)
tokio = {version = "1.19.2", features = ["io-util", "macros", "time", "rt-multi-thread"]}
tokio-serial = "5.4.1"

**Comment by ZanderBrown** [comment]
The answer would appear to be that you need the `libudev` feature

**Comment by archfz** [comment]
But I am pretty sure I had libudev installed before adding serialport also to required packages, as I was previously using serialport by itself, just that I switched to tokio as I started needing async.

**Comment by vdominguez1993** [comment]
I had the same issue but ad @ZanderBrown mentioned you just need the `libudev` feature. Remember this is related to the Cargo.toml of your project. Use the tokio-serial dependency like this: `tokio-serial = { version = "5.4.3", features = ["libudev"] }`

I confirm this fixed the problem for me.

**Comment by archfz** [comment]
Oh I understand now. I thought you meant libudev package. Will try it and come back.

**Comment by archfz** [comment]
It worked, thanks.
