### ISSUE TITLE
Simultanous read and write

### ISSUE THREAD

**Issue by miker1423** [berkowski/tokio-serial#64]
Hello,
Is it possible to have a task awaiting a read while another task writes? I have a usecase where I need to send packets but I can also receive at any point, so I need to be able to simultanously wait for any read operation but be able to write to the same port.

I'm receiving the data to send through a mpsc channel so technically I can use a `future::select` to change between the futures depending on which resolves first, but just wanted to know if it's possible to have it in two separate tasks sharing the same port.

Thanks!

**Comment by edrose-tewke** [comment]
Which interface are you using for the serial port?

I've been using `SerialStream` and the `AsyncReadExt`/`AsyncWriteExt` traits for performing async IO on the serial port, but I can't use both of those in a `select!` block at the same time. Both use `&mut self` and you can't mutably borrow the same item in more than one place.

I'm interested in whether I'm just fundamentally doing something wrong, or whether there is some workaround for this.

**Comment by ndusart** [comment]
@edrose-tewke you could try using [`tokio::io::split`](https://docs.rs/tokio/latest/tokio/io/fn.split.html) on your `SerialStream`.

It will consume it and return it splitted in two objects,  an `AsyncRead` and an `AsyncWrite`. You'll own each of them independently then and you'll be able to use both of them in different branches of your `select!`.

**Comment by edrose-tewke** [comment]
@ndusart Amazing - thank you! I hoped that there was something simple that I was missing.

**Comment by barafael** [comment]
@miker1423 @berkowski I believe this issue can be closed.
