### ISSUE TITLE
Make tokio-serial compatible with "reformed" tokio usage

### ISSUE THREAD

**Issue by snorp** [berkowski/tokio-serial#8]
I think this mainly means tokio-serial should accept a tokio::reactor::Handle and stop using tokio_core and tokio_io.

**Comment by berkowski** [comment]
I haven't been following tokio development for a few months now but I do need to cut a release to at lest track changes in the `mio-serial`.

I'll look into this "reformed" usage stuff -- any blog posts or such to check out besides just looking through the official docs?

**Comment by lnicola** [comment]
https://aturon.github.io/2018/02/27/futures-0-2-RC/
https://tokio.rs/blog/2018-02-tokio-reform-shipped/

Or something like this. I haven't really looked into the changes myself, though.

**Comment by berkowski** [comment]
Ok, thanks.  I've got a few plane flights this week -- looks like I've got some reading now.
